name: test

on:
  push:
    branches: [main]

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/update-package-version
        with:
          version: "0.2.0"
          package: packages/sample
          commit_message_template: sample v$VERSION
          tag_template: sample@$VERSION
          tag_force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
